config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :users, only: [:index, :show]
  resources :teams, except: :index
  resources :boards do
    resources :lists, except: [:index, :show] do
      put :sort
    end
    resources :cards, except: [:index] do
      put :sort
      resources :comments, only: [:create]
    end
  end
  resources :rooms, only: [:index, :show, :create]
  resources :messages, only: [:create]
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :cards, dependent: :destroy
  validates :name, presence: true, length: { maximum: 10 }

  include RankedModel 
  ranks :row_order , with_same: :board_id 
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board
  before_action :set_list, only: [:edit, :update, :destroy]

  def new
  end

  def create
    @list = List.create(list_params)
    respond_to do |format|
      format.html { redirect_to board_path(@board) }
      format.json
    end
  end

  def edit
  end

  def update
    @list.update(list_params)
    redirect_to board_path(@board)
  end

  def destroy
    @list.destroy
    redirect_to board_path(@board)
  end

  def sort
    list = List.find(params[:list_id])
    list.update(list_params)
    render body: nil
  end

  private

  def set_board
    @board = Board.find(params[:board_id])
  end

  def list_params
    params.require(:list).permit(:name, :row_order_position).merge(board_id: params[:board_id])
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/views/lists/_list-form.html.haml
.modal-dialog{:role => "document"}
  .modal-content
    .modal-header
      %h5#exampleModalLongTitle.modal-title 
      %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
        %span{"aria-hidden" => "true"} ×
    .modal-body
      = form_for [@board, @list], remote: true do |f|
        .form-group
          = f.label :name, class: 'form-controll-label'
          %br/
          = f.text_field :name, class: 'form-controll'

        .modal-footer
          %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
          = f.submit "Save", class: "btn btn-primary"

app/views/lists/_list.html.haml
.list{data: { model_name: list.class.name.underscore, update_url: board_list_sort_path(@board.id, list.id)}}
  .list__name
    = list.name
  .list__icon
    = link_to edit_board_list_path(@board.id, list.id), remote: true do
      = icon 'fas', 'edit', class: "icon"
    = link_to board_list_path(@board.id, list.id), method: :delete, "data-dismiss" => "modal", data: { confirm: "リストを削除しますか？", commit: "DELETE", cancel: "Cancel"}, title: "DELETE List" do
      = icon 'fas', 'trash-alt', class: "icon"
  .list__cards
    = render list.cards.rank(:row_order)

app/views/lists/edit.js.erb
$("#list-form").html("<%= escape_javascript(render 'list-form') %>")
$("#list-form").modal("show")

app/views/lists/update.js.erb
$(".list-items").html("<%= escape_javascript(render @lists ) %>")
$("#list-form").modal("hide")