config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :users, only: [:index, :show]
  resources :teams, except: :index
  resources :boards do
    resources :lists, except: [:index, :show] do
      put :sort
    end
    resources :cards, except: [:index] do
      put :sort
      resources :comments, only: [:create]
    end
  end
  resources :rooms, only: [:index, :show, :create]
  resources :messages, only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boards
  has_many :card_users, dependent: :destroy
  has_many :cards, through: :card_users
  has_many :team_users, dependent: :destroy
  has_many :teams, through: :team_users
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :comments

  validates :name, presence: true, length: { maximum: 10 }

  has_one_attached :image

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.where(name: (params[:keyword])).where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @user = User.find(params[:id])
    @cards = @user.cards.includes(:card).order("deadline DESC")
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
end

app/views/users/show.html.haml
.mypage
  .profile
    .profile__inner
      .profile__image
        = user_icon_large(@user)
      .profile__name
        = @user.name
        - if @user.id == current_user.id
          = link_to edit_user_registration_path do
            = icon 'fas', 'edit', class: 'icon'
        - else
          - if @isRoom == true
            = link_to room_path(@roomId) do
              = icon 'far', 'envelope', class: 'icon'
          - else
            = form_for @room do |f|
              = fields_for @entry do |e|
                = e.hidden_field :user_id, value: @user.id
              = f.submit "DM", class: "btn btn-secondary btn-sm"
        .profile__about
          - if @user.about.present?
            = @user.about

  %ul.tab
    %li.tab__menu.active Team
    %li.tab__menu Cards

  .tab__area
    .tab__area__contents.show
      - if @user.teams.present?
        - @user.teams.each do |team|
          .tab__area__content
            = link_to team_path(team) do
              = team_icon_small(team)
              = team.name

    .tab__area__contents
      - if @user.teams.present?
        - @user.teams.each do |team|
          .team-name.bold
            = team.name
          -if team.boards.present?
            - team.boards.each do |board|
              .board-name
                = link_to "#{board.name}", board_path(board.id)
                %div
                - if @user.cards.present?
                  - @user.cards.each do |card|
                    - if card.list.board_id == board.id
                      .card-info
                        .card__title.bold
                          = link_to "#{card.name}", board_card_path(board.id, card.id), remote: true
                          #card-show.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
                        - if card.deadline.present?
                          .card__icon
                            = icon 'far', 'clock'
                            = card.deadline
                        .card__icons
                          - if card.comments.present?
                            .card__icon
                              = icon 'far', 'comment'
                              = card.comments.length
                          - if card.users.present?
                            .card__icon
                              = icon 'far', 'user'
                              = card.users.length
                          - if (card.finish == "doing")
                            .card__icon
                              = icon 'fas', 'running'
                          - else
                            .card__icon__done
                              = icon 'fas', 'check'