config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :users, only: [:index, :show]
  resources :teams, except: :index
  resources :boards do
    resources :lists, except: [:index, :show] do
      put :sort
    end
    resources :cards, except: [:index] do
      put :sort
      resources :comments, only: [:create]
    end
  end
  resources :rooms, only: [:index, :show, :create]
  resources :messages, only: [:create]
end

app/views/shared/_alert.html.haml
- if notice
  .alert.alert-info
    = notice
    %button{type: "button", class: "close", "data-dismiss" => "alert"}
      &times;
- elsif alert
  .alert.alert-danger
    = alert
    %button{type: "button", class: "close", "data-dismiss" => "alert"}
      &times;

app/views/shared/_board-menu.html.haml
%nav.navbar.navbar-expand-lg
  .navbar-brand
    = @board.name
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        - if @board.team_id.present?
          .nav-link
            = link_to "#{@board.team.name}", team_path(@board.team.id), class: "nav-link"
        - else
          .nav-link
            = link_to "Personal", user_path(@board.user.id), class: "nav-link"
      %li.nav-item
        - if @board.team_id.present?
          .nav-link
            - @board.team.users.each do |user|
              = link_to user_path(user) do
                = user_icon_small(user)
                %p.icon-user
                  = user.name
      %li.nav-item
        - if @board.deadline.present?
          .nav-link.disable
            = icon 'far', 'clock'
            = @board.deadline
      %li.nav-item
        .nav-link
          = link_to "Add Card", new_board_card_path(@board.id), remote: true, class: "btn btn-outline-secondary btn-sm"
          #card-form.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}

    .nav-item.my-2.my-lg-0.dropdown
      %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
        Board Menu
      .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
        = link_to "Edit Board", edit_board_path(@board.id), class: "dropdown-item"
        = link_to "Delete Board", board_path(@board.id), method: :delete, class: "dropdown-item", "data-dismiss" => "modal", data: { confirm: "ボードを削除しますか？", commit: "DELETE", cancel: "Cancel"}, title: "DELETE Board"

app/views/shared/_navbar.html.haml
- if user_signed_in?
  %nav.navbar.navbar-expand-lg.navbar-light.bg-light
    %a.navbar-brand{:href => "/"} Task-manager
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li.nav-item.active
          = link_to "My Page", user_path(current_user.id), class: "nav-link"
          %span.sr-only (current)
        %li.nav-item
          = link_to "Boards", boards_path, class: "nav-link"
        %li.nav-item
          = link_to "Messages", rooms_path, class: "nav-link"
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Add
          .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            = link_to "Board", new_board_path, class: "dropdown-item"
            = link_to "Team", new_team_path, class: "dropdown-item"
        %li.nav-item
          = link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link"

- else
  %nav.navbar.navbar-expand-lg.navbar-light.bg-light
    %a.navbar-brand{:href => "/"} Task-manager
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li.nav-item
          = link_to "Sign up", new_user_registration_path, class: "nav-link"
        %li.nav-item
          = link_to "Log in", new_user_session_path, class: "nav-link"