config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :users, only: [:index, :show]
  resources :teams, except: :index
  resources :boards do
    resources :lists, except: [:index, :show] do
      put :sort
    end
    resources :cards, except: [:index] do
      put :sort
      resources :comments, only: [:create]
    end
  end
  resources :rooms, only: [:index, :show, :create]
  resources :messages, only: [:create]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
  has_many :card_users, dependent: :destroy
  has_many :users, through: :card_users
  has_many :comments, dependent: :destroy
  has_many_attached :images
  validates :name, presence: true, length: { maximum: 20 }

  enum finish: {doing: false, done!: true}

  include RankedModel 
  ranks :row_order , with_same: :list_id 
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def show
    @comment = Comment.new
    @comments = @card.comments.includes(:user).order("created_at DESC")
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to board_path(@board)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to board_path(@board)
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to board_path(@board)
  end

  def sort
    card = Card.find(params[:card_id])
    card.update(card_params)
    render body: nil
  end

  private

  def set_board
    @board = Board.find(params[:board_id])
  end

  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:name, :about, :deadline, :finish, :list_id, :row_order_position, images: [], user_ids: [])
  end
end

app/views/cards/_card-form.html.haml
.modal-dialog{:role => "document"}
  .modal-content
    .modal-header
      %h5#exampleModalLongTitle.modal-title 
      %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
        %span{"aria-hidden" => "true"} ×
    .modal-body
      = form_for [@board, @card], remote: true do |f|
        - if @card.errors.any?
          .form__errors
            %h3= "#{@card.errors.full_messages.count}件のエラーが発生しました。"
            %ul
              - @card.errors.full_messages.each do |message|
                %li= message
        .form-group
          = f.label :name, class: 'form-control-label'
          %br/
          = f.text_field :name, class: 'form-control'
        .form-group
          = f.label :about, class: 'form-control-label'
          %br/
          = f.text_area :about, class: 'form-control'
        .form-group
          = f.label :list_id, class: 'form-control-label'
          %br/
          = f.collection_select :list_id, @board.lists.all, :id, :name, class: 'form-control'
        .form-group
          = f.label :deadline, class: 'form-control-label'
          %br/
          = f.date_field :deadline, class: 'form-control'
        - if @board.team.present?
          .form-group
            = f.label :"Assined Member", class: 'form-control-label'
            %br/
            .check-box
              = f.collection_check_boxes :user_ids, @board.team.users.all, :id, :name
        .form-group
          = f.label :"Are you done this Task?", class: 'form-control-label'
          %br/
          = f.select :finish, Card.finishes.keys, {}, class: 'form-controll'
        .modal-footer
          %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
          = f.submit "Save", class: "btn btn-primary"

app/views/cards/_card-show.html.haml
.modal-dialog{:role => "document"}
  .modal-content
    .modal-header
      %h5#exampleModalLongTitle.modal-title 
        = card.name
      %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
        %span{"aria-hidden" => "true"} ×
    .modal-body
      .card__content [説明]
      .card__content__child
        = card.about
      .card__content [メンバー]
      .card__content__child
        - card.users.each do |user|
          = user_icon_small(user)
          %p.icon-user
            = user.name
      .card__content [期限]
      .card__content__child
        = card.deadline
      .card__content [完了状態]
      .card__content__child
        = card.finish

      .card__content [添付ファイル]
      .card__images
        - if card.images
          - card.images.each do |image|
            = image_tag image, class: "card-image"
      .card__content__child
        = form_for [@board, @card] do |f|
          .form-group
            = f.file_field :images, multiple: true
            = f.submit "Save File", class: "btn btn-primary btn-sm"
      .card__content [コメント]
      .card__content__child
        = form_for [@board, @card, @comment] do |f|
          .form-group
            = f.text_area :text, class: 'form-control', placeholder: "write comments"
            = f.submit "Submit", class: "btn btn-primary btn-sm"
      .comments
        - if comments
          - comments.each do |comment|
            .comment
              .comment-user
                = user_icon_small(comment.user)
              .comment-time
                = comment.created_at.strftime("%Y/%m/%d %H:%M")
              .comment-text
                = comment.text
    .modal-footer
      %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
      = link_to 'Edit Card', edit_board_card_path(@board), remote: true, class: 'btn btn-success', "data-dismiss" => "modal"
      #card-form.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
      = link_to 'DELETE', board_card_path(@board), method: :delete, class: 'btn btn-danger', "data-dismiss" => "modal", data: { confirm: "カードを削除しますか？", commit: "DELETE", cancel: "Cancel"}, title: "DELETE Card"

app/views/cards/_card.html.haml
.card{data: { model_name: card.class.name.underscore, update_url: board_card_sort_path(@board.id, card.id)}}
  .card__title.bold
    = link_to "#{card.name}", board_card_path(@board, card), remote: true, class: "card__title"
    #card-show.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  
  - if card.deadline.present?
    .card__icon
      = icon 'far', 'clock'
      = card.deadline
  .card__icons
    - if card.comments.present?
      .card__icon
        = icon 'far', 'comment'
        = card.comments.length
    - if card.users.present?
      .card__icon
        = icon 'far', 'user'
        = card.users.length
    - if (card.finish == "doing")
      .card__icon
        = icon 'fas', 'running'
    - else
      .card__icon__done
        = icon 'fas', 'check'

app/views/cards/edit.js.erb
$("#card-form").html("<%= escape_javascript(render 'card-form') %>")
$("#card-form").modal("show")

app/views/cards/new.js.erb
$("#card-form").html("<%= escape_javascript(render 'card-form') %>")
$("#card-form").modal("show")

app/views/cards/show.js.erb
$("#card-show").html("<%= escape_javascript(render 'card-show', card: @card, comments: @comments) %>")
$("#card-show").modal("show")